export const SEARCH_SEQUENCE = [
  '> INITIALIZING SEARCH AGENT...',
  '> EXECUTING LIVE QUERIES...',
  '> PARSING REMOTE STREAMS...',
  '> FILTERING SIGNAL NOISE...',
  '> AGGREGATING RESULTS...',
];
